language: node_js




install:
- npm install -g vsce
- npm install -g typescript
- npm install -g gulp
- npm install


script:
- gulp tslint;
- npm run compile;

deploy:
- provider: releases
  api_key: $GIT_TOKEN
  file_glob: true
  file: "*.vsix"
  skip_cleanup: true
  on:
    tags: true