language: node_js


install:
- npm install;

script:
- npm install -g gulp;
- gulp;
- npm compile

after_success:
- npm install -g vsce;
- vsce package;

deploy:
- provider: releases
  api_key: $GIT_TOKEN
  file_glob: true
  file: "*.vsix"
  skip_cleanup: true
  on:
    tags: true